version: '3'
services:
  app: 
    container_name: appnode
    restart: always
    build: .
    ports:
      - "5000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app

  mongo:
    container_name: bdmongo
    image: mongo
    ports:
      - "27018:27017"
    logging:
      driver: none

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWPRD: clave
        ME_CONFIG_MONGODB_URL: mongodb://root:clave@mongo:27017/
